### PR TITLE
Change background

### LINKED ISSUE #11: Use different background to astropy
We probably want to differentiate the projects, so later on it would be good to use a slightly different project rather than simply re-use the astropy one. However, this is not critical and doesn't have to be done before the deadline.

### PR DESCRIPTION
**Pull request by eteq**
This changes the background to something a bit more "general" than the current version, which is from astropy. This has a sun (which nominally includes atomic transitions, right? ;), astrophysics, and results from a simulation, which I think is a good representative background.  The sun is a bit poorly blended, but I'm not up to blending it better than that in the time remaining.

Nominally I think this closes #11 ? @atrofrog ?

### CODE REVIEW

**Comment by dpshelio** [comment]
Ouch... that Sun on the left looks that needs a bit of gimp-blending.... I think I prefer the one we have...

@astrofrog I think @eteq wanted to ping you in this one.

**Comment by Cadair** [comment]
@Alex-Ian-Hamilton ping

**Comment by eteq** [comment]
This one is a bit more blended, although still not perfect.  But it's best if you look at it on the web site - it looks less awkward there because it looks sort of logo-y.

I'd really rather it not be using the same as astropy a la #11 .  If someone else wants to take a shot feel free - source images are https://solarsystem.nasa.gov/multimedia/gallery/PIA03149.jpg and http://cdn4.sci-news.com/images/enlarge/image_1196_1e-milky-way.jpg (both NASA public domain images)

**Comment by eteq** [comment]
@astrofrog @Alex-Ian-Hamilton  @Cadair @dpshelio  - so what do you think of this version?  Still too hash of a blending or is it ok?

**Pull request closed without merging**
