### PR TITLE
Add EinsteinPy to OpenAstronomy

### PR DESCRIPTION
**Pull request by shreyasbapat**
As discussed over chats with @Cadair  :)  

Please let me know if something is required.

### CODE REVIEW

**Comment by shreyasbapat** [comment]
And I think this: https://github.com/OpenAstronomy/openastronomy.github.io/wiki/New-member-on-Open-Astronomy definitely needs an update.

**Comment by shreyasbapat** [comment]
Thanks a ton @dpshelio :) 
I was busy in exams, so could not reply. Looking forward to see it merged :)

**Comment by shreyasbapat** [comment]
Hi @dpshelio , any updates on this? :D

**Comment by mirca** [comment]
Hi @shreyasbapat! Thank you for wanting to join OpenAstronomy with EinsteinPy! I'm positive this PR is well put together, so it will be merged sooner or later :)

**Comment by Cadair** [comment]
The steering council is in the process of coming up with a set of membership criteria (which I am pretty sure you will easily meet) but we don't want to accept new members till it's in place. Sorry for the delay!

**Comment by Cadair** [comment]
Sorry this one took so long @shreyasbapat :sob:

**Comment by shreyasbapat** [comment]
It's completely fine. Thanks all of you😀

Is there some formality which needs to be done?

**Pull request merged**
