### PR TITLE
Sunspotter/SunPy idea for SOCIS

### PR DESCRIPTION
**Pull request by dpshelio**
@drsophiemurray @Samaloney @mbobra - I'm adding you all as co-mentors. Though only one needs to be mentioned to SOCIS. Let me know if you are happy with this (deadline is tonight, but we can change this later).

This idea was created for SOCIS for its AI theme.

### CODE REVIEW

**Comment by Cadair** [comment]
Lgtm

**Comment by dpshelio** [comment]
@Cadair - could you approve it? :innocent:  (mostly the last change, so you don't appear by duplicate on the mentor list... though you would, in fact, be more than one!)

**Comment by drsophiemurray** [comment]
Would be great to finally do something with this dataset 😆

**Comment by mbobra** [comment]
I agree with @drsophiemurray ! I'm in :)

**Pull request merged**
