### PR TITLE
remove the openastronomy slack because nobody uses it

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by bsipocz** [comment]
Does it exists? I would definitely prefer it over the matrix channel, it's a real pain to log into two systems so in reality I only log in there when want to DM certain people.

**Comment by dpshelio** [comment]
:man_shrugging: If slack makes it easier to people (and doesn't make @Cadair to suffer to run the bridge) then I'm happy to keep it.

**Comment by bsipocz** [comment]
Yes it does make it easier I think for anyone who are using it anyway for work stuff. But my question still stands. The workspace was mentioned in the webpage, but not a way to get sign up. So that one need to be sorted out for sure.

**Comment by Cadair** [comment]
If we are after providing a slack window into `#openastronomy:openastronomy.org` on matrix, I would much rather bridge it into the astropy slack than nob about with bridging a whole different slack team

**Comment by bsipocz** [comment]
@Cadair - I'm not sure I understand your comment. Which slack team do you propose to bridge over? (overall I wouldn't care about the details once I'm able to connect via slack...)

**Comment by Cadair** [comment]
I mean let's make a channel in the astropy slack and bridge it to the matrix room, using the existing bridge.

**Comment by bsipocz** [comment]
We can do that, but what about rather rebrand the pyastro slack to be openastronomy? That one is already been bridge, too, isn't it?

**Comment by bsipocz** [comment]
hmm, so should we open an openastronomy channel on the pyastro slack, and you would bridge openastronomy there? how does that sound? Or revive openastronomy (that I have no idea who created, and when etc)

**Comment by Cadair** [comment]
Well people have been using it so that's why I closed this.

**Comment by bsipocz** [comment]
yes, and no. At least I don't have access to the openastronomy slack. people are using pyastro, but then the openastronomy matrix room is not bridged anywhere(?).

**Comment by Cadair** [comment]
Ze and Erik have been using the openastronomy slack to bridge to #openastronomy:openastronomy.org on matrix.

**Comment by bsipocz** [comment]
interesting

**Pull request closed without merging**
