### PR TITLE
Porting Stingray to Julia

### PR DESCRIPTION
**Pull request by matteobachetti**
@giordano this is the project we discussed. Let me know if it is feasible for you in the framework of a GSoC large project
@dhuppenkothen any comments are welcome

### CODE REVIEW

**Review by bsipocz — APPROVED** [review]
I'm approving this, really nice fit for GSoC, but waiting for the OK from @giordano before merging.

**Review by giordano — APPROVED** [review]
Ok with me :+1:

**Comment by bsipocz** [comment]
Thank you both, we have our first project idea for 2022 🎉

**Comment by bsipocz** [comment]
Never to merge from the phone!

@dpshelio @mirca - I'm sorry, but the rendering for this is not working. I've already removed the file to have the `md` extension, but it didn't do the trick. If you have any some to have a look at this, a fix would be appreciated.

**Pull request merged**
