### PR TITLE
fixes #170(added meta and og tags)

### LINKED ISSUE #170: No meta and og tags in the header
There is no meta tags and og tags in the header of the website. We require them for better SEO. I will like to work on it.

### PR DESCRIPTION
**Pull request by sarnava1**
Added meta and og tags in head.html for better SEO.

Fixes #170

### CODE REVIEW

**Comment by sarnava1** [comment]
@bsipocz @Cadair @dpshelio please review my PR.

**Comment by nabobalis** [comment]
Do you need this PR? #173 has the same code as this one and adds the favicon.

**Comment by sarnava1** [comment]
@nabobalis sorry! Actually, there was some mistake during opening the PR. Keeping in mind the contributing guidelines I di not want to solve both issues in one PR. I tried to follow one PR per issue.

**Comment by nabobalis** [comment]
@sarnava1 That's fine then.

**Comment by sarnava1** [comment]
@nabobalis thank you. Are they okay? This is the first time I am contributing to OpenAstronomy project and hope to continue further.

**Comment by dpshelio** [comment]
@sarnava1 thanks for your PRs! Please, could you put both on #169, update the title accordingly and closed this one? That includes both. We are ok with solving multiple issues on the same PR.

**Comment by sarnava1** [comment]
@dpshelio ok! I am closing this one since https://github.com/OpenAstronomy/openastronomy.github.io/pull/173 has both the issues solved. Thank you.

**Pull request closed without merging**
