### PR TITLE
added RADIS projects

### PR DESCRIPTION
**Pull request by erwanp**
Better late than never @dpshelio

### CODE REVIEW

**Comment by bsipocz** [comment]
@erwanp - student application deadline is less a day away, so this ship has unfortunately sailed. Please do keep these in mind for next year.

**Comment by erwanp** [comment]
Hi @bsipocz . Can we still try to get these through? It's unlikely there'll be any applicants in time but who knows?

**Comment by pkj-m** [comment]
Hi @erwanp, I found your message on the OA matrix channel which led me here. I understand the student application deadline is almost here, but I wanted to let you know that this project sounds like something I could contribute to in a meaningful way. I was planning to apply for GSoC under OpenAstronomy earlier (under sunpy, more specifically) and have some precontributions to sunpy, but finally dropped the idea due to a mismatch between my skills and those demanded by the projects.

However, given the requirements for this project, I believe I should be able to tackle it head first. I am quite proficient in both python and CUDA and have past experience in open-source and package development (thanks to Julia Summer of Code). Please let me know if this project could be considered for GSoC 2020 as I'd love to work on this during summer.

**Comment by pkj-m** [comment]
Also tagging @bsipocz. Please let me know if this could work out?

**Comment by erwanp** [comment]
> 
> 
> Hi @erwanp, I saw your message on the OA matrix channel. I understand the student application deadline is almost here, but I wanted to let you know that this project sounds like something I could contribute to in a meaningful way. I was planning to apply for GSoC under OpenAstronomy earlier (under sunpy, more specifically) and have some precontributions to sunpy, but finally dropped the idea due to a mismatch between my skills and those demanded by the projects.
> 
> However, given the requirements for the project "Accelerate Synthetic Spectra Calculations", I believe I should be able to tackle it head first. I am quite proficient in both python and CUDA and have past experience in open-source and package development (thanks to Julia Summer of Code). Please let me know if this project could be considered for GSoC 2020 as I'd love to work on this during summer.

Thanks @pkj-m for keeping the boat afloat! 

This is our first time applying for GSoC, so there may be extra workload for the OpenAstronomy Admin team and I would totally understand if they cannot let this through. 

I'd suggest you start working on a proposal in case this gets accepted. Let's see! 

Also, @dcmvdbekerom above is the co-mentor on the project and the one who came up with most of the ideas. You may want to get in touch with him!

**Comment by adityabharadwaj198** [comment]
Hey @erwanp, I'm interested in working on the 'RADIS Atmosphere Calculation Interface' project. I have previous python and CUDA experience. Is RADIS's acceptance as a sub-org still doubtful?

**Comment by erwanp** [comment]
Just created a Gitter/GSoC2020 room, adding you there to continue the discussion.

**Comment by bsipocz** [comment]
OK, let's reopen this, but I'm very firmly on the stand that this last minute addition of a new suborg is not going to work.

**Comment by dpshelio** [comment]
After deliberating with the @OpenAstronomy/gsoc-admin - This is being accepted and merged now. However, this is only allowed now due to the worldwide circumstances that are happening at the moment and not to be repeated in the future.

**Comment by erwanp** [comment]
Thank you @OpenAstronomy/gsoc-admin !

**Pull request merged**
