### PR TITLE
Added in Helioviewer developer's github username

### PR DESCRIPTION
**Pull request by wafels**
As suggested, the Helioviewer developer's github username

### CODE REVIEW

**Comment by bsipocz** [comment]
Oh, there are no sufficient words to describe how much I hate this github conflict resolution, but whatever, I go against my principles and did it here now rather than rebase.

Merge this one away once CI is happy.

**Comment by bsipocz** [comment]
Thanks @wafels and @Helioviewer-Kirill!

**Comment by Cadair** [comment]
Chalk that up as personal growth :p

**Comment by bsipocz** [comment]
🤣 
Yeah, as opposed to libraries, I'm  not that sensitive to hacky commit history in website repos as the whole stuff is a big hack anyway with fluffy CSS nonsense.

**Pull request merged**
