### PR TITLE
project idea: astropy - photutils

### PR DESCRIPTION
**Pull request by hamogu**
Implement PSF photometry for fitting several overlapping objects at once

### CODE REVIEW

**Comment by taldcroft** [comment]
Seems like a good idea to me.  I wonder if @larrybradley or @bsipocz have any comments?

**Comment by bsipocz** [comment]
Ideally it would be great to have a good PSF photometry tool in photutils. 

However I don't feel comfortable mentoring this project (though can be a lousy co-mentor). So it really depends on @larrybradley and someone from astropy.modeling, and/or @adonath @cdeil as they worked on the earlier version before.

**Comment by cdeil** [comment]
FYI: I want to focus on Gammapy this year (see #28) and @adonath doesn't want to mentor at all, so we're not available as mentors / co-mentors for photutils.

**Comment by larrybradley** [comment]
@bsipocz There is work going on now on the photutils PSF models/fitting by @hamogu and @eteq (and others at STScI).  However, that work is focussed on low-level utilities and models and not on building a high-level PSF fitting tool.  I agree that it would be great to have such a tool in photutils.  I have very limited experience in PSF fitting, so I'm not really the right person to be the primary mentor.  Perhaps @eteq is interested?

@hamogu Is the issue with "just fit a model with hundreds of parameters....usually fails" that the initial guesses are wrong or the PSF model is wrong (or both)?  To do a simultaneous fit, I think you have to fit a compound model of many PSFs to the data.  Is there any other way?

**Comment by hamogu** [comment]
@larrybradley : Yes, at some point you have to do a fit with many parameters, but one can be a little clever about it. For example, DAOPHOT uses an algorithm that goes about like this: Run a source detection (and we have several of those in photutils already), then do some scheme to split that into groups (*) of at most N stars and then fit the psfs for those stars. Thus, instead of lets say one fit with 500 parameters you get 50 fits with an average of 10 parameters. That will (a) converge much faster and (b) the lower dimensionality of the parameter space allows the fit algorithm to explore it more fully and thus reduce the chance of hitting obscure local minima and (c) makes it a little safer the presence of a spatially varying background, because each group covers only a fraction of the total image.

Obviously, there is some user interaction in here in picking the right parameters and splitting into groups of a reasonable size, but where still all sources that overlap end up the the same group.
In my vision for photutils that's OK. I think we aim for some exploring and interactivity, some hands on data reduction - that's were the strength of python is. Users looking for a fully automated methods for millions of sources with lots of other complexity to handle all sorts of corner cases are probably better served with the LSST software stack than photutils.
(And LSST has probably more full-time software developers than photutils has total contributors.)

(*): That's of course the tricky bit. There are several possible approaches and I don't remember exactly what DAOPHOT does (that's why I listed "look how existing codes like DAOPHOT and sextractor deal with that" in the project description), but one way would be similar to a watershed algorithm: Mark a region around each source that's 3 * FWHM wide and find groups of sources with overlapping regions. Those will be fit together. Other approaches could be a minimum spanning forest, build from the single minimum spanning tree with all branches with length > 3 FWHM cut or one could smooth out the entire image and make groups along the countour that is "x * std(background)".

Sounds like I might be a reasonable mentor for this if we take it...

**Comment by taldcroft** [comment]
OK, starting from a prior list of candidate source positions makes this a tractable project for an intermediate (to expert) student.  I think an intermediate student will require quite a bit of mentor guidance as to how to proceed.

On a philosophical note (which is unrelated to accepting this as a project idea), I'm not so keen on having an interactive element to source detection and photometry.  Having been involved in a large survey which did just that (and even helping out by making a GUI that allowed for hand-visualization of thousands of sources), the result was entirely unreproducible.  This then flowed down to an inability to generate meaningful detection sensitivity maps, etc.  But I do understand the challenges and see first hand in the CXC how difficult full automation actually is.

**Comment by hamogu** [comment]
@taldcroft : I think we mean something when we say "interactive" and "exploring".
(I know the project you are talking about...)

The way I used DAOPHOT before (and I envision something similar here) was: Pick a few representative fields, run the photometry with my best guesses for the parameters (e.g. detection threshold for source detection, outlier rejection, branch length to cut for group splitting, background model, etc. ) and see what you get. Play with those parameters until you find something that works for your instrument / object type / data quality combination. Then run the photometry with those parameters for all fields / exposures you have. Last step: Look where it failed (e.g. I had a field that was a lot more crowded than the others) and either adjust the parameters and do it again or find some other solution for the few fields with problems (e.g. ignore them if it turns out that the signal there is much weaker to to clouds as I had it).

No GUIs, please! (For the philosophical reasons cited by @taldcroft and a few others he did not mention.)

**Comment by taldcroft** [comment]
Perhaps more to the point, @hamogu would you be willing to mentor?  As mentioned earlier we can merge this (after a rebase), but we do want to identify a primary mentor in the next 10 days.

**Comment by hamogu** [comment]
updated according to the discussion here and rebased.

**Pull request merged**
