### PR TITLE
Added link to openastronomy in the top

### PR DESCRIPTION
**Pull request by dpshelio**
To do so I needed to create an empty page with a new label `redirect` so
when the page gets loaded it redirects to the other "website".

### CODE REVIEW

**Comment by dpshelio** [comment]
This would close OpenAstronomy/Universe_OA#5

**Comment by Cadair** [comment]
lgtm

**Comment by dpshelio** [comment]
Intenational Golf Travel Maker??? what?? ah no, wait! the first is a lower case `L`...  so you mean this
[LGTM](http://lgtm.in/i/8MahUvilq)

**Comment by Cadair** [comment]
:+1: amazing

**Pull request merged**
