### PR TITLE
Added a closed PR to the project for future reference.  

### PR DESCRIPTION
**Pull request by nabobalis**
Unsure if this is how it works on this repo.

### CODE REVIEW

**Comment by bsipocz** [comment]
@nabobalis - I don't know the answer for your question, let's see it.

**Comment by nabobalis** [comment]
Thanks again!

**Comment by bsipocz** [comment]
Well, this didn't work. So I would suggest to either list it under issues, or go ahead and modify the CSS to have a new filed for PRs (or just simply rewrite the "Related issues" to "Related issues and pull requiests").

**Comment by nabobalis** [comment]
I will move it somewhere else

**Pull request merged**
