### PR TITLE
Adding calendar

### PR DESCRIPTION
**Pull request by bmorris3**
cc @eteq @dpshelio. Temporarily fixes issue #163

### CODE REVIEW

**Comment by bmorris3** [comment]
I'm adding events to the calendar now.

**Comment by bsipocz** [comment]
On the long term my vision would be to have a staticly rendered (or a duplicate) page that just list what's happening given it's not that easy to plan ahead with having only the google calendar.

**Comment by bsipocz** [comment]
@bmorris3 - I can't find the calendar settings anywhere, could you please add edit right to my other e-mail address, too? (sipoczbrigitta@gmail)

**Comment by bmorris3** [comment]
I can't find them either? Lemme experiment...

**Comment by dpshelio** [comment]
I've added you again @bsipocz to the OpenAstronomy - events calendar

**Comment by bsipocz** [comment]
thanks!

**Pull request merged**
