### PR TITLE
GSOC 2018 interop coords

### PR DESCRIPTION
**Pull request by hamogu**
@taldcroft @mhvk How about we go again for the second part - coordinates? I'll have a slightly different flavour to is, because there is no fits standard that we can implement exactly. Instead this would be about gracefully degrading information, by e.g. makeing is easy to convert a full mixin coordiante column to a simple RA, DEC pair of two normal columns that I can then print in latex.

Are you available to support that again?

### CODE REVIEW

**Comment by mhvk** [comment]
@hamogu - yes, I can help with it, though like last year it will be a bit on-and-off (in particular, I expect to be on holidays most of August). The scope is slightly less well-defined, and part of the problem has been solved with @taldcroft's nice new mixin-protocol for FITS. But I think there is enough left.

**Comment by taldcroft** [comment]
@hamogu - I'm a bit ambivalent, and so maybe I'm not understanding the idea fully.  As @mhvk mentioned, the exact problem that you state in the idea text is (in my opinion) fully solved in 3.0.  If you have an coordinate object and store to FITS or ECSV it already gets broken down into RA and Dec columns (e.g. for spherical representation) with the expected values.  This round-trips precisely, *and* can be read in by non-astropy tools with just loss of metadata.  The catch in the 3.0 implementation is that it takes an end-run around FITS.  Since there is no standard for coordinates this seems reasonable.

So I think that much of this project would be defining a FITS standard to serialize coordinates without the use of the "hammer" of just storing all meta-data in a serialized YAML structure.    We had long discussions last year about just adding one single FITS keyword, so I don't know about an entire FITS standard and whether we can find the right GSoC student to invent it.  I would say the requirements would include "substantial expertise in FITS and WCS" unless *we* want to define the standard.

**Comment by dpshelio** [comment]
We are just 9 days away to the students deadline!! if you want your idea to get visibility then you should agree what to do with this idea soonish so students can write a good application.

**Comment by taldcroft** [comment]
@dpshelio - I talked with @hamogu in person about this and I'm not entirely fired up about it.  At this point it's for @hamogu to decide where to go on this.

**Pull request closed without merging**
