### PR TITLE
reorder list of orgs based on gsoc participation and alphabetically

### PR DESCRIPTION
**Pull request by mirca**
addresses #252 cc @bsipocz 

Screenshot 2020-02-22 at 9 48 11 AM
Screenshot 2020-02-22 at 9 48 35 AM

### CODE REVIEW

**Comment by bsipocz** [comment]
timelab and juliaastro is also part of gsoc, but glue is not really (or it's borderline, I take the sunglue project a sunpy one rather than a glue one).

But it either case, let's see what others think about, my original idea may be bad to begin with :)

**Comment by mirca** [comment]
> But it either case, let's see what others think about, my original idea may be bad to begin with :)

sure :) I've moved ``juliaastro`` and ``timelab`` to the first pack just in case.

**Comment by bsipocz** [comment]
OK, I say we go with it. If anyone else have opinions strong enough to open a PR, please do a follow-up one.

**Comment by bsipocz** [comment]
(I've also added a commit with the new matrix link for astronomy-commons, that case it doesn't need another round to get it merged).

**Pull request merged**
