### PR TITLE
Adding DIRAC/astronomy-commons ideas

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by bsipocz** [comment]
@stevenstetzler - please add the ideas as separate files (e.g. in a PR to this PR, or DM-ing them to me). There can also be a timeline included, for examples see the sunpy project ideas: https://github.com/OpenAstronomy/openastronomy.github.io/pull/240

As a rule, we need at least two mentors per project, I assume @mjuric will be your second mentor for those, unless there is someone else willing to step in.

**Comment by bsipocz** [comment]
@cadair - do you have any idea of what happened to giles for this repo?

**Comment by bsipocz** [comment]
@parejko @manodeep - You've already gave me the thumbs up for this elsewhere, but nevertheless let me know if to change anything in for the idea.

**Comment by manodeep** [comment]
@bsipocz Yup - I am in. 

I will note that we might need `Cython` (and potentially even C) for the project

**Comment by bsipocz** [comment]
OK, I've added cython.

**Comment by manodeep** [comment]
Thanks @bsipocz

**Comment by mjuric** [comment]
@bsipocz Happy to be the second mentor.

**Comment by bsipocz** [comment]
@Cadair @dpshelio @mirca - please do approve and merge this.

**Comment by Cadair** [comment]
> @Cadair - do you have any idea of what happened to giles for this repo?

Should have been fixed in #244

**Pull request merged**
